/* Generated By:JavaCC: Do not edit this line. SPL1Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SPL1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 6;
  /** RegularExpression Id. */
  int RBRACE = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int PRODUCTLINE = 10;
  /** RegularExpression Id. */
  int FEATURENAME = 11;
  /** RegularExpression Id. */
  int EXTENDS = 12;
  /** RegularExpression Id. */
  int AS = 13;
  /** RegularExpression Id. */
  int FORMULA = 14;
  /** RegularExpression Id. */
  int PRODUCT = 15;
  /** RegularExpression Id. */
  int ROOT_TYPE = 16;
  /** RegularExpression Id. */
  int MANDATORY_TYPE = 17;
  /** RegularExpression Id. */
  int OPTIONAL_TYPE = 18;
  /** RegularExpression Id. */
  int ALTERNATIVE_TYPE = 19;
  /** RegularExpression Id. */
  int OR_TYPE = 20;
  /** RegularExpression Id. */
  int ASSIGN = 21;
  /** RegularExpression Id. */
  int IMPLIES = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int OR = 24;
  /** RegularExpression Id. */
  int NOT = 25;
  /** RegularExpression Id. */
  int IDENTIFIER = 26;
  /** RegularExpression Id. */
  int LETTER = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"PL\"",
    "\"FeatureName\"",
    "\"extends\"",
    "\"as\"",
    "\"Formula\"",
    "\"Product\"",
    "\"ROOT\"",
    "\"MANDATORY\"",
    "\"OPTIONAL\"",
    "\"ALTERNATIVE\"",
    "\"OR\"",
    "\"=\"",
    "\"implies\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
