/* Generated By:JavaCC: Do not edit this line. SPL1Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SPL1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int LBRACE = 8;
  /** RegularExpression Id. */
  int RBRACE = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int PRODUCTLINE = 12;
  /** RegularExpression Id. */
  int FEATURENAME = 13;
  /** RegularExpression Id. */
  int EXTENDS = 14;
  /** RegularExpression Id. */
  int AS = 15;
  /** RegularExpression Id. */
  int FORMULA = 16;
  /** RegularExpression Id. */
  int PRODUCT = 17;
  /** RegularExpression Id. */
  int ROOT_TYPE = 18;
  /** RegularExpression Id. */
  int MANDATORY_TYPE = 19;
  /** RegularExpression Id. */
  int OPTIONAL_TYPE = 20;
  /** RegularExpression Id. */
  int ALTERNATIVE_TYPE = 21;
  /** RegularExpression Id. */
  int OR_TYPE = 22;
  /** RegularExpression Id. */
  int OFOT = 23;
  /** RegularExpression Id. */
  int SOFOT = 24;
  /** RegularExpression Id. */
  int AIFL = 25;
  /** RegularExpression Id. */
  int SIZE = 26;
  /** RegularExpression Id. */
  int COVERAGE = 27;
  /** RegularExpression Id. */
  int TEST = 28;
  /** RegularExpression Id. */
  int ASSIGN = 29;
  /** RegularExpression Id. */
  int IMPLIES = 30;
  /** RegularExpression Id. */
  int AND = 31;
  /** RegularExpression Id. */
  int OR = 32;
  /** RegularExpression Id. */
  int NOT = 33;
  /** RegularExpression Id. */
  int IDENTIFIER = 34;
  /** RegularExpression Id. */
  int LETTER = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"PL\"",
    "\"FeatureName\"",
    "\"extends\"",
    "\"as\"",
    "\"Formula\"",
    "\"Product\"",
    "\"ROOT\"",
    "\"MANDATORY\"",
    "\"OPTIONAL\"",
    "\"ALTERNATIVE\"",
    "\"OR\"",
    "\"ofot\"",
    "\"sofot\"",
    "\"aifl\"",
    "\"size\"",
    "\"coverage\"",
    "\"test?\"",
    "\"=\"",
    "\"implies\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
